#include "MainWindow.h"
#include "ControlPanelWidget.h"
#include "DashboardWidget.h"
#include "DataViewerWidget.h"
#include <QApplication>
#include <QDockWidget>
#include <QMenuBar>
#include <QShortcut>
#include <QStatusBar>
#include <QVBoxLayout>
MainWindow::MainWindow(QWidget* parent):QMainWindow(parent),dashboard_(new DashboardWidget),controls_(new ControlPanelWidget),viewer_(new DataViewerWidget){setWindowTitle("Premium Content Radar / 全网黄金内容雷达"); resize(1280,760); auto* central=new QWidget; auto* layout=new QVBoxLayout(central); layout->addWidget(dashboard_); layout->addWidget(viewer_); setCentralWidget(central); auto* dock=new QDockWidget("Controls / 控制",this); dock->setWidget(controls_); addDockWidget(Qt::LeftDockWidgetArea,dock); database_.open("wechat_radar.db"); connect(controls_,&ControlPanelWidget::filtersChanged,this,&MainWindow::refreshData); menuBar()->addAction("Load Samples / 加载示例",this,&MainWindow::loadSampleData); new QShortcut(QKeySequence(Qt::Key_Escape),this,SLOT(refreshData())); new QShortcut(QKeySequence(Qt::CTRL | Qt::Key_S),this,SLOT(refreshData())); applyTheme(); loadSampleData();}
void MainWindow::applyTheme(){qApp->setStyleSheet("QMainWindow,QWidget{background:#0d1117;color:#f0f6fc;font-family:'Inter','Segoe UI','PingFang SC';} QTableView{background:#161b22;alternate-background-color:#1e1e2e;gridline-color:#30363d;} QHeaderView::section{background:#252538;color:#f0f6fc;padding:6px;border:1px solid #30363d;} QPushButton,QComboBox,QLineEdit{background:#161b22;color:#f0f6fc;border:1px solid #30363d;border-radius:8px;padding:6px;} QSlider::groove:horizontal{height:6px;background:#30363d;border-radius:3px;} QSlider::handle:horizontal{background:#58a6ff;width:14px;border-radius:7px;}");}
void MainWindow::loadSampleData(){database_.addSeed("gh_seed_001","Deep Insight Lab","Technology"); ContentRecord a; a.title="AI Agents Are Changing Content Discovery"; a.accountName="Deep Insight Lab"; a.gzhId="gh_seed_001"; a.category="Technology"; a.url="https://example.local/article/1"; a.readNum=120000; a.likeNum=5200; a.oldLikeNum=1800; a.commentNum=430; a.articleCount30d=18; database_.enqueueArticle(a); ContentRecord b; b.title="High-density Comment Signals in WeChat Articles"; b.accountName="Radar Notes"; b.gzhId="gh_seed_002"; b.category="Media"; b.url="https://example.local/article/2"; b.readNum=76000; b.likeNum=2100; b.oldLikeNum=900; b.commentNum=390; b.articleCount30d=9; database_.enqueueArticle(b); database_.flush(); refreshData(); statusBar()->showMessage("Sample records loaded / 示例数据已加载");}
void MainWindow::refreshData(){viewer_->proxy()->setWeights(controls_->engagementWeight(),controls_->commentWeight(),controls_->frequencyWeight()); viewer_->proxy()->setMinimums(controls_->minimumRead(),1.0); auto rows=database_.listArticles(); viewer_->setRecords(rows); double top=0.0; for(int i=0;i<rows.size();++i) top=qMax(top,viewer_->proxy()->scoreForSourceRow(i)); dashboard_->setMetrics(2,rows.size(),top);}
