#include "UiText.h"

#include <QHash>

QString UiText::text(const QString& key, UiLanguage language) {
  static const QHash<QString, QString> en = {
      {"app.title", "Premium Content Radar"},
      {"dock.title", "Control Center"},
      {"tab.filters", "Filters"}, {"tab.discover", "Keyword Discovery"}, {"tab.phone", "Phone Diagnostics"}, {"tab.production", "Production Suite"}, {"tab.auto", "Auto Ingestion"}, {"tab.seeds", "Seeds"}, {"tab.wechat", "WeChat"}, {"tab.logs", "Logs"}, {"tab.guide", "Guide"},
      {"menu.file", "File"}, {"menu.plugins", "Plugins"}, {"menu.actions", "Actions"}, {"menu.help", "Help"},
      {"action.load_samples", "Load Samples"}, {"action.export_articles_csv", "Export Articles CSV"}, {"action.export_articles_json", "Export Articles JSON"}, {"action.export_seeds_csv", "Export Seeds CSV"},
      {"action.load_plugins", "Load Plugins"}, {"action.preview", "Preview"}, {"action.star_seed", "Star Seed"}, {"action.bridge_smoke", "Send Bridge Smoke Payload"}, {"action.reset", "Reset Controls"},
      {"action.language", "中文"}, {"action.show_control_center", "Show Control Center"}, {"action.about", "About"}, {"action.manual", "Built-in User Manual"},
      {"tip.language", "Switch the whole software UI between English and Chinese. The current language is stored in local settings."},
      {"tip.load_samples", "Insert safe sample records into the local SQLite database for demo and testing."},
      {"tip.export_articles_csv", "Export the current article library to a CSV file."},
      {"tip.export_articles_json", "Export the current article library to a JSON file."},
      {"tip.load_plugins", "Load content provider plugins from the configured plugin directory."},
      {"tip.preview", "Open and inspect the currently selected article."},
      {"tip.star_seed", "Save the selected article publisher into the seed pool."},
      {"tip.bridge_smoke", "Send sample metric and comment payloads to the localhost bridge to verify ingestion."},
      {"tip.reset", "Reset filters, keyword, weights, and minimum read threshold."}, {"tip.show_control_center", "Reopen the left Control Center if it was closed."},
      {"filter.industry", "Industry"}, {"filter.keyword", "Keyword"}, {"filter.engagement", "Engagement weight"}, {"filter.comment", "Comment weight"}, {"filter.frequency", "Frequency weight"}, {"filter.min_read", "Minimum reads"},
      {"filter.keyword.placeholder", "Keyword"}, {"filter.all", "All"}, {"filter.technology", "Technology"}, {"filter.finance", "Finance"}, {"filter.lifestyle", "Lifestyle"},
      {"tip.filter.industry", "Filter articles by publisher category."}, {"tip.filter.keyword", "Search article title, account name, category, or URL."}, {"tip.filter.engagement", "Adjust how much reads and likes affect the score."}, {"tip.filter.comment", "Adjust how much comment density affects the score."}, {"tip.filter.frequency", "Adjust how much publishing frequency affects the score."}, {"tip.filter.min_read", "Hide articles below this read-count threshold."},
      {"data.title", "Title"}, {"data.account", "Account"}, {"data.category", "Category"}, {"data.publish_time", "Publish Time"}, {"data.read", "Read"}, {"data.like", "Like"}, {"data.old_like", "Old Like"}, {"data.comment", "Comment"}, {"data.freq", "30d Frequency"}, {"data.score", "Score"}, {"data.url", "URL"},
      {"tip.data.table", "Sortable article table. Select one row, then use Preview or Star Seed."},

      {"discover.intro", "Keyword-first path: use search keywords to find hot WeChat articles before choosing accounts. This is the primary discovery route; seed accounts are a secondary route."}, {"discover.keywords", "Search keywords"}, {"discover.min_read", "Minimum reads"}, {"discover.min_like", "Minimum likes"}, {"discover.min_comment", "Minimum comments"}, {"discover.min_hot_score", "Minimum hot score"}, {"discover.max_candidates", "Max per keyword"}, {"discover.results", "Discovered hot-article candidates"},
      {"discover.start_keyword_auto", "Start Keyword Auto Ingestion"}, {"discover.auto_search", "Auto Search"}, {"discover.generate_search_urls", "Generate Search URLs"}, {"discover.import_results", "Import Results JSON"}, {"discover.enqueue_hot", "Add Hot Results to Queue"}, {"discover.keywords_placeholder", "Paste keywords, one per line, for example AI tools, local life, cross-border ecommerce, crypto trading."},
      {"discover.col.keyword", "Keyword"}, {"discover.col.title", "Title"}, {"discover.col.account", "Account"}, {"discover.col.read", "Read"}, {"discover.col.like", "Like"}, {"discover.col.score", "Hot Score"}, {"discover.col.url", "URL"},
      {"tip.discover.keywords", "Keywords are independent from the seed pool. Use broad market terms when you do not yet know which accounts to track."}, {"tip.discover.start_keyword_auto", "After the phone is connected and USB debugging is authorized, automatically search keywords, apply the hot-article metric controls, enqueue matched candidates, and open them with ADB."}, {"tip.discover.auto_search", "Automatically fetch search result pages and parse WeChat article candidate URLs."}, {"tip.discover.generate", "Generate external WeChat search entry URLs for debugging."}, {"tip.discover.import", "Import sanitized JSON containing title, url, account, read_num, like_num, and comment_num."}, {"tip.discover.enqueue", "Append candidates that satisfy read, like, comment, and hot-score controls to the ADB auto-ingestion queue."},

      {"auto.enable", "Automation gate"}, {"auto.enable_checkbox", "Allow ADB URL opening for this session"}, {"auto.interval", "Open interval (seconds)"}, {"auto.attempts", "Max attempts per URL"}, {"auto.urls", "Article URL list"}, {"auto.queue", "Auto-ingestion queue"},
      {"auto.add_urls", "Add URLs"}, {"auto.start", "Start Auto Ingestion"}, {"auto.stop", "Stop"}, {"auto.run_next", "Run Next Now"}, {"auto.clear_completed", "Clear Opened"}, {"auto.clear_all", "Clear All"}, {"auto.save_queue", "Save Queue"}, {"auto.load_queue", "Load Queue"},
      {"auto.urls_placeholder", "Paste one WeChat article URL per line, for example https://mp.weixin.qq.com/s/xxxx . The scheduler opens these URLs on your connected test phone through adb; metrics still enter through the local proxy bridge."},
      {"auto.col.status", "Status"}, {"auto.col.attempts", "Attempts"}, {"auto.col.account", "Account"}, {"auto.col.category", "Category"}, {"auto.col.last", "Last Attempt"}, {"auto.col.url", "URL / Error"},
      {"tip.auto.enable", "Explicit safety gate. Keep it off unless adb is installed, a dedicated test phone is connected, and local proxy capture is configured."}, {"tip.auto.interval", "Delay between two ADB article-open commands. Use a conservative value to avoid UI churn and network pressure."}, {"tip.auto.attempts", "How many times a failed URL may be retried."}, {"tip.auto.urls", "Only WeChat article URLs are accepted. Cookies, tokens, headers, and raw captures are never required here."}, {"tip.auto.start", "Start opening queued URLs through adb. The proxy adapter must already be running to capture metrics."}, {"tip.auto.run_next", "Open exactly one runnable queued URL now for testing."},
      {"seed.gzh", "GZH ID"}, {"seed.name", "Name"}, {"seed.category", "Category"}, {"seed.count30d", "30d"}, {"seed.score", "Score"},
      {"seed.placeholder.gzh", "gh_xxx"}, {"seed.placeholder.name", "Account name"}, {"seed.add", "Add or Update Seed"}, {"seed.remove", "Remove Selected"}, {"seed.export", "Export Seeds CSV"},
      {"tip.seed.gzh", "Original Official Account ID used for deduplication."}, {"tip.seed.name", "Human-readable publisher name."}, {"tip.seed.category", "Publisher category used by filters and reports."}, {"tip.seed.add", "Create or update a seed publisher in the local database."}, {"tip.seed.remove", "Remove the selected seed from the local database."}, {"tip.seed.export", "Export all seeds to CSV."}, {"tip.seed.table", "Seed pool table. Select a row before removing it."},
      {"wechat.database", "SQLite database"}, {"wechat.plugin_dir", "Plugin directory"}, {"wechat.port", "Local bridge port"}, {"wechat.browse", "Browse"}, {"wechat.adb", "Enable ADB automation"}, {"wechat.samples", "Load sample data on startup"}, {"wechat.save", "Save runtime settings"}, {"wechat.test", "Send local bridge smoke payload"}, {"wechat.log", "Runtime log"},
      {"tip.wechat.database", "Local SQLite file that stores articles and seeds."}, {"tip.wechat.plugin_dir", "Directory containing provider plugins."}, {"tip.wechat.port", "Localhost TCP port for compact JSON ingestion."}, {"tip.wechat.adb", "Enable only with a dedicated test phone and explicit authorization."}, {"tip.wechat.samples", "Load demo records when the app starts."}, {"tip.wechat.save", "Persist settings to the local user configuration file."}, {"tip.wechat.test", "Verify the bridge with safe sample payloads."}, {"tip.wechat.log", "Sanitized runtime messages and ingestion events."},
      {"dash.accounts", "Scanned Accounts"}, {"dash.detections", "Premium Detections"}, {"dash.top_score", "Top Score"},
      {"manual.title", "Built-in User Manual"},
      {"manual.body", "1. Start with the WeChat tab. Confirm the database path, plugin directory, and bridge port. Keep ADB disabled unless you use a dedicated test phone.\n\n2. Click Save runtime settings, then Load Plugins. The WeChat provider starts a localhost bridge.\n\n3. Click Send Bridge Smoke Payload. If the article table grows, local ingestion works.\n\n4. Primary route: open Keyword Discovery, enter market keywords, import sanitized hot-result JSON, then add hot results to the auto queue. For URL-based automatic ingestion, open the Auto Ingestion tab. Paste one WeChat article URL per line, enable the ADB safety gate, and click Run Next Now or Start Auto Ingestion. The scheduler only opens URLs on your connected test phone; metrics still enter through the local proxy bridge.\n\n5. Choose an ingestion option. Option A uses a lawful local proxy adapter. Option B imports manually prepared JSON or CSV. Option C uses ADB only to open pages on a test phone, then still imports metrics through A or B.\n\n6. Use Filters to tune category, keyword, score weights, and minimum reads. The score combines engagement, comment density, and publishing frequency.\n\n7. Select an article row. Preview opens the URL and shows the main metrics. Star Seed saves the publisher into the seed pool.\n\n8. Use Seeds to maintain target publishers. Add or update by GZH ID, name, and category. Export seeds when you need a backup.\n\n9. Use File exports to save articles as CSV or JSON. Review exports before production decisions.\n\n10. Security boundary: never store cookies, headers, tokens, certificates, or raw packet captures in the repository. Only compact sanitized JSON should be sent to 127.0.0.1."},
  

    {"suite.tab.proxy", "Proxy Wizard"}, {"suite.tab.replay", "Replay Center"}, {"suite.tab.health", "Health Monitor"}, {"suite.tab.scoring", "Scoring Studio"}, {"suite.tab.workspace", "Workspace & Reports"}, {"suite.tab.privacy", "Privacy Center"},
    {"suite.proxy_intro", "P0: Configure and verify the lawful local proxy adapter path. The goal is to prove that the phone can reach the computer, the bridge is ready, and WeChat metric/comment interfaces are observed before production ingestion."},
    {"suite.proxy_port", "Proxy port"}, {"suite.bridge_port", "Bridge port"}, {"suite.phone_reachable", "Phone can reach this computer"}, {"suite.metric_hit", "Metric interface observed"}, {"suite.comment_hit", "Comment interface observed"}, {"suite.run_proxy", "Run Proxy Wizard"},
    {"suite.replay_intro", "P1: Replay sanitized JSON/JSONL samples so ingestion, scoring, reports, and UI can be tested without repeatedly depending on a live phone session."},
    {"suite.replay_placeholder", "Paste sanitized JSON, JSON array, or JSONL. Example: {\"title\":\"Case\",\"account_name\":\"Demo\",\"read_num\":10000,\"comment_num\":80,\"url\":\"https://mp.weixin.qq.com/s/demo\"}"}, {"suite.replay_run", "Replay Samples"},
    {"suite.health_intro", "P1: Monitor phone, proxy, bridge, database, and task queue health. Green means ready, yellow means risk, red means blocked."}, {"suite.health_refresh", "Refresh Health"},
    {"suite.scoring_intro", "P2: Configure the hot-content scoring model and preview how records, accounts, and keywords are ranked."}, {"suite.score_read", "Read weight"}, {"suite.score_like", "Like weight"}, {"suite.score_comment", "Comment weight"}, {"suite.score_old_like", "Old-like weight"}, {"suite.score_original", "Originality weight"}, {"suite.score_preview", "Preview Scores"},
    {"suite.workspace_intro", "P3: Manage a business workspace, generate decision reports, and export a sanitized support snapshot."}, {"suite.workspace_placeholder", "Workspace name, for example AI tools / local life / cross-border ecommerce"}, {"suite.report_generate", "Generate Report"}, {"suite.snapshot_export", "Export Diagnostic Snapshot"},
    {"suite.privacy_intro", "P3: Explain what the software does and does not collect. This page is used before production deployment or team handoff."},
    {"suite.col.status", "Status"}, {"suite.col.item", "Item"}, {"suite.col.detail", "Detail"}, {"suite.col.fix", "Fix Guidance"},
    {"phone.intro", "Check every layer required for fully automatic keyword ingestion: ADB, USB authorization, phone shell control, article opening, local proxy, and bridge readiness."},
    {"phone.serial", "Target phone"}, {"phone.proxy_port", "Proxy port (0 = skip)"}, {"phone.test_url", "Test URL"},
    {"phone.include_open_test", "Include open-link test in full diagnostics"}, {"phone.run", "Run Full Diagnostics"},
    {"phone.restart_adb", "Restart ADB"}, {"phone.open_link", "Test Open Link"}, {"phone.copy_report", "Copy Report"},
    {"phone.export_json", "Export JSON"}, {"phone.col.status", "Status"}, {"phone.col.item", "Item"},
    {"phone.col.details", "Details"}, {"phone.col.fix", "Fix Guidance"}, {"phone.col.raw", "Raw Output"},
    {"tip.phone.run", "Run P0/P1/P2 phone readiness checks and explain each blocker."},
    {"tip.phone.restart_adb", "Run adb kill-server and adb start-server, then diagnose again."},
    {"tip.phone.open_link", "Send an Android VIEW intent to the selected phone using the test URL."},
    {"tip.phone.copy_report", "Copy a text report for support or troubleshooting."},
    {"tip.phone.export_json", "Export the full structured diagnostics report as JSON."},
};
  static const QHash<QString, QString> zh = {
      {"app.title", "全网黄金内容雷达"},
      {"dock.title", "控制中心"},
      {"tab.filters", "筛选"}, {"tab.discover", "关键词发现"}, {"tab.phone", "手机诊断"}, {"tab.production", "生产中心"}, {"tab.auto", "自动采集"}, {"tab.seeds", "种子池"}, {"tab.wechat", "微信接入"}, {"tab.logs", "日志"}, {"tab.guide", "说明书"},
      {"menu.file", "文件"}, {"menu.plugins", "插件"}, {"menu.actions", "操作"}, {"menu.help", "帮助"},
      {"action.load_samples", "加载示例数据"}, {"action.export_articles_csv", "导出文章 CSV"}, {"action.export_articles_json", "导出文章 JSON"}, {"action.export_seeds_csv", "导出种子 CSV"},
      {"action.load_plugins", "加载插件"}, {"action.preview", "预览文章"}, {"action.star_seed", "收藏为种子"}, {"action.bridge_smoke", "发送本地桥冒烟载荷"}, {"action.reset", "重置控件"},
      {"action.language", "English"}, {"action.show_control_center", "打开控制中心"}, {"action.about", "关于"}, {"action.manual", "内置使用说明书"},
      {"tip.language", "在中文和英文之间切换整个软件界面，当前语言会保存到本地配置。"},
      {"tip.load_samples", "向本地 SQLite 数据库插入安全示例记录，用于演示和测试。"},
      {"tip.export_articles_csv", "把当前文章库导出为 CSV 文件。"},
      {"tip.export_articles_json", "把当前文章库导出为 JSON 文件。"},
      {"tip.load_plugins", "从已配置的插件目录加载内容提供者插件。"},
      {"tip.preview", "打开并查看当前选中文章的详情。"},
      {"tip.star_seed", "把当前选中文章的公众号保存到种子池。"},
      {"tip.bridge_smoke", "向本地桥发送示例指标和评论载荷，验证接入链路。"},
      {"tip.reset", "重置筛选条件、关键词、评分权重和最低阅读阈值。"}, {"tip.show_control_center", "控制中心被关闭后，用这个入口重新打开左侧控制中心。"},
      {"filter.industry", "行业"}, {"filter.keyword", "关键词"}, {"filter.engagement", "互动权重"}, {"filter.comment", "评论权重"}, {"filter.frequency", "频率权重"}, {"filter.min_read", "最低阅读"},
      {"filter.keyword.placeholder", "关键词"}, {"filter.all", "全部"}, {"filter.technology", "科技"}, {"filter.finance", "财经"}, {"filter.lifestyle", "生活"},
      {"tip.filter.industry", "按公众号分类筛选文章。"}, {"tip.filter.keyword", "搜索文章标题、账号名称、分类或链接。"}, {"tip.filter.engagement", "调整阅读数和点赞数对评分的影响。"}, {"tip.filter.comment", "调整评论密度对评分的影响。"}, {"tip.filter.frequency", "调整发文频率对评分的影响。"}, {"tip.filter.min_read", "隐藏阅读数低于该阈值的文章。"},
      {"data.title", "标题"}, {"data.account", "账号"}, {"data.category", "分类"}, {"data.publish_time", "发布时间"}, {"data.read", "阅读"}, {"data.like", "点赞"}, {"data.old_like", "在看"}, {"data.comment", "评论"}, {"data.freq", "30天频率"}, {"data.score", "评分"}, {"data.url", "链接"},
      {"tip.data.table", "可排序文章表格。先选中一行，再使用预览文章或收藏为种子。"},

      {"discover.intro", "关键词优先路径：先用关键词发现爆款微信文章，再决定追踪哪些账号。这是主要发现路线；种子池是第二路线。"}, {"discover.keywords", "搜索关键词"}, {"discover.min_read", "最低阅读"}, {"discover.min_like", "最低点赞"}, {"discover.min_comment", "最低评论"}, {"discover.min_hot_score", "最低爆款分"}, {"discover.max_candidates", "每词最多候选"}, {"discover.results", "已发现爆款候选"},
      {"discover.start_keyword_auto", "开始关键词自动采集"}, {"discover.auto_search", "自动搜索"}, {"discover.generate_search_urls", "生成搜索入口"}, {"discover.import_results", "导入结果 JSON"}, {"discover.enqueue_hot", "爆款结果加入队列"}, {"discover.keywords_placeholder", "粘贴关键词，每行一个，例如 AI工具、本地生活、跨境电商、虚拟货币交易。"},
      {"discover.col.keyword", "关键词"}, {"discover.col.title", "标题"}, {"discover.col.account", "账号"}, {"discover.col.read", "阅读"}, {"discover.col.like", "点赞"}, {"discover.col.score", "爆款分"}, {"discover.col.url", "链接"},
      {"tip.discover.keywords", "关键词不依赖种子池。不知道该抓哪个公众号时，先用市场关键词找爆款文章。"}, {"tip.discover.start_keyword_auto", "手机已连接并授权 USB 调试后，自动搜索关键词，按爆款指标控件筛选候选文章，入队并用 ADB 自动打开。"}, {"tip.discover.auto_search", "自动请求搜索结果页并解析微信公众号文章候选链接。"}, {"tip.discover.generate", "生成外部微信搜索入口，主要用于调试。"}, {"tip.discover.import", "导入包含 title、url、account、read_num、like_num、comment_num 的精简 JSON。"}, {"tip.discover.enqueue", "把满足阅读、点赞、评论和爆款分控件的候选文章追加到 ADB 自动采集队列。"},

      {"auto.enable", "自动化安全开关"}, {"auto.enable_checkbox", "允许本次会话使用 ADB 打开 URL"}, {"auto.interval", "打开间隔（秒）"}, {"auto.attempts", "每条 URL 最大尝试次数"}, {"auto.urls", "文章 URL 列表"}, {"auto.queue", "自动采集队列"},
      {"auto.add_urls", "添加 URL"}, {"auto.start", "开始自动采集"}, {"auto.stop", "停止"}, {"auto.run_next", "立即执行下一条"}, {"auto.clear_completed", "清理已打开"}, {"auto.clear_all", "清空全部"}, {"auto.save_queue", "保存队列"}, {"auto.load_queue", "加载队列"},
      {"auto.urls_placeholder", "每行粘贴一个微信文章链接，例如 https://mp.weixin.qq.com/s/xxxx。调度器会通过 adb 在已连接测试手机上逐篇打开；阅读、点赞、评论等指标仍由本地代理桥接入。"},
      {"auto.col.status", "状态"}, {"auto.col.attempts", "尝试"}, {"auto.col.account", "账号"}, {"auto.col.category", "分类"}, {"auto.col.last", "上次尝试"}, {"auto.col.url", "链接 / 错误"},
      {"tip.auto.enable", "显式安全开关。只有在已安装 adb、已连接专用测试手机、并配置好本地代理抓取时才打开。"}, {"tip.auto.interval", "两次 ADB 打开文章命令之间的间隔。建议保守设置，避免界面抖动和网络压力。"}, {"tip.auto.attempts", "单条 URL 失败后最多重试多少次。"}, {"tip.auto.urls", "这里只接受微信文章链接，不需要 Cookie、Token、Header 或原始抓包。"}, {"tip.auto.start", "开始用 adb 逐篇打开队列 URL。代理适配器必须已经运行，才能捕获指标。"}, {"tip.auto.run_next", "只立即打开一条可执行 URL，用于测试链路。"},
      {"seed.gzh", "公众号ID"}, {"seed.name", "名称"}, {"seed.category", "分类"}, {"seed.count30d", "30天"}, {"seed.score", "评分"},
      {"seed.placeholder.gzh", "gh_xxx"}, {"seed.placeholder.name", "账号名称"}, {"seed.add", "添加或更新种子"}, {"seed.remove", "删除选中"}, {"seed.export", "导出种子 CSV"},
      {"tip.seed.gzh", "公众号原始 ID，用于去重。"}, {"tip.seed.name", "便于识别的公众号名称。"}, {"tip.seed.category", "用于筛选和报告的公众号分类。"}, {"tip.seed.add", "在本地数据库中创建或更新种子公众号。"}, {"tip.seed.remove", "从本地数据库删除选中的种子。"}, {"tip.seed.export", "把全部种子导出为 CSV。"}, {"tip.seed.table", "种子池表格，删除前需要先选中一行。"},
      {"wechat.database", "SQLite 数据库"}, {"wechat.plugin_dir", "插件目录"}, {"wechat.port", "本地桥端口"}, {"wechat.browse", "浏览"}, {"wechat.adb", "启用 ADB 自动化"}, {"wechat.samples", "启动时加载示例数据"}, {"wechat.save", "保存运行配置"}, {"wechat.test", "发送本地桥冒烟载荷"}, {"wechat.log", "运行日志"},
      {"tip.wechat.database", "保存文章和种子的本地 SQLite 文件。"}, {"tip.wechat.plugin_dir", "内容提供者插件所在目录。"}, {"tip.wechat.port", "接收精简 JSON 的 localhost TCP 端口。"}, {"tip.wechat.adb", "只有在使用专用测试手机并明确授权时才启用。"}, {"tip.wechat.samples", "软件启动时加载演示记录。"}, {"tip.wechat.save", "把配置持久化到本地用户配置文件。"}, {"tip.wechat.test", "用安全示例载荷验证本地桥。"}, {"tip.wechat.log", "脱敏运行消息和接入事件。"},
      {"dash.accounts", "已扫描账号"}, {"dash.detections", "高价值发现"}, {"dash.top_score", "最高评分"},
      {"manual.title", "内置使用说明书"},
      {"manual.body", "1. 先进入微信接入页，确认数据库路径、插件目录和本地桥端口。除非使用专用测试手机，否则保持 ADB 关闭。\n\n2. 点击保存运行配置，然后加载插件。微信 Provider 会启动 localhost 本地桥。\n\n3. 点击发送本地桥冒烟载荷。如果文章表新增记录，说明本地接入链路可用。\n\n4. 主要路线：进入关键词发现页，输入市场关键词，导入脱敏爆款结果 JSON，再把爆款结果加入自动队列。URL 自动采集路线：进入自动采集页。每行粘贴一个微信文章 URL，打开 ADB 安全开关，然后点击立即执行下一条或开始自动采集。调度器只负责在已连接测试手机上打开文章，指标仍通过本地代理桥接入。\n\n5. 选择接入方案。方案 A 使用合法的本地代理适配器；方案 B 导入人工准备的 JSON 或 CSV；方案 C 只用 ADB 在测试手机上打开页面，指标仍通过 A 或 B 导入。\n\n6. 使用筛选页调整行业、关键词、评分权重和最低阅读数。评分综合互动、评论密度和发文频率。\n\n7. 选中文章行后，预览文章会打开链接并显示主要指标；收藏为种子会把该公众号保存到种子池。\n\n8. 在种子池页维护目标公众号。按公众号 ID、名称和分类添加或更新，需要备份时导出种子。\n\n9. 通过文件菜单把文章导出为 CSV 或 JSON。做生产决策前先复核导出结果。\n\n10. 安全边界：不要把 Cookie、Header、Token、证书或原始抓包保存到仓库。软件只应接收发送到 127.0.0.1 的精简脱敏 JSON。"},
  

    {"suite.tab.proxy", "代理向导"}, {"suite.tab.replay", "回放中心"}, {"suite.tab.health", "健康监控"}, {"suite.tab.scoring", "评分工作台"}, {"suite.tab.workspace", "工作区和报告"}, {"suite.tab.privacy", "隐私中心"},
    {"suite.proxy_intro", "P0：配置并验证合法本地代理适配器链路。目标是在生产采集前证明手机能访问电脑、本地桥已就绪，并且已经观察到微信指标和评论接口。"},
    {"suite.proxy_port", "代理端口"}, {"suite.bridge_port", "本地桥端口"}, {"suite.phone_reachable", "手机可以访问这台电脑"}, {"suite.metric_hit", "已观察到指标接口"}, {"suite.comment_hit", "已观察到评论接口"}, {"suite.run_proxy", "运行代理向导"},
    {"suite.replay_intro", "P1：回放脱敏 JSON/JSONL 样本，不必每次依赖真实手机会话，就能测试接入、评分、报告和界面。"},
    {"suite.replay_placeholder", "粘贴脱敏 JSON、JSON 数组或 JSONL。例如：{\"title\":\"案例\",\"account_name\":\"演示账号\",\"read_num\":10000,\"comment_num\":80,\"url\":\"https://mp.weixin.qq.com/s/demo\"}"}, {"suite.replay_run", "回放样本"},
    {"suite.health_intro", "P1：监控手机、代理、本地桥、数据库和任务队列健康状态。绿色代表就绪，黄色代表风险，红色代表阻塞。"}, {"suite.health_refresh", "刷新健康状态"},
    {"suite.scoring_intro", "P2：配置爆款内容评分模型，并预览文章、账号、关键词排序变化。"}, {"suite.score_read", "阅读权重"}, {"suite.score_like", "点赞权重"}, {"suite.score_comment", "评论权重"}, {"suite.score_old_like", "在看权重"}, {"suite.score_original", "原创权重"}, {"suite.score_preview", "预览评分"},
    {"suite.workspace_intro", "P3：管理业务工作区，生成决策报告，并导出不含隐私凭证的诊断快照。"}, {"suite.workspace_placeholder", "工作区名称，例如 AI工具 / 本地生活 / 跨境电商"}, {"suite.report_generate", "生成报告"}, {"suite.snapshot_export", "导出诊断快照"},
    {"suite.privacy_intro", "P3：说明软件会采集什么、不会采集什么。生产部署或团队交接前先看这里。"},
    {"suite.col.status", "状态"}, {"suite.col.item", "项目"}, {"suite.col.detail", "详情"}, {"suite.col.fix", "修复指引"},
    {"phone.intro", "检查关键词全自动采集所需的每一层：ADB、USB 授权、手机 shell 控制、文章链接打开、本地代理、本地桥就绪状态。"},
    {"phone.serial", "目标手机"}, {"phone.proxy_port", "代理端口（0=跳过）"}, {"phone.test_url", "测试链接"},
    {"phone.include_open_test", "全量诊断时包含打开链接测试"}, {"phone.run", "一键全量诊断"},
    {"phone.restart_adb", "重启 ADB"}, {"phone.open_link", "测试打开链接"}, {"phone.copy_report", "复制报告"},
    {"phone.export_json", "导出 JSON"}, {"phone.col.status", "状态"}, {"phone.col.item", "项目"},
    {"phone.col.details", "详情"}, {"phone.col.fix", "修复指引"}, {"phone.col.raw", "原始输出"},
    {"tip.phone.run", "执行 P0/P1/P2 手机就绪检测，并解释每个阻塞点。"},
    {"tip.phone.restart_adb", "执行 adb kill-server 和 adb start-server，然后重新诊断。"},
    {"tip.phone.open_link", "向选中手机发送 Android VIEW intent，打开测试链接。"},
    {"tip.phone.copy_report", "复制文本诊断报告，方便排障或发给技术支持。"},
    {"tip.phone.export_json", "导出完整结构化 JSON 诊断报告。"},
};
  const auto& dict = language == UiLanguage::Chinese ? zh : en;
  return dict.value(key, key);
}
